### ISSUE TITLE
BOZ literal constant at (1) cannot appear in an array constructor and Symbol 'd_qnan' at (1) has no IMPLICIT type

### ISSUE THREAD

**Issue by gzyasdafaegfea** [MESAHub/mesa#680] opened 2024-07-15 03:30 UTC
I am a second-year student, and I encountered problems while installing MESA on my Ubuntu 22.04 system。The error message is as follows：
Error: BOZ literal constant at (1) cannot appear in an array constructor
../private/suzuki_tables.f90:612:30:

612 |          table % data = d_qnan
|                              1
Error: Symbol 'd_qnan' at (1) has no IMPLICIT type
make: *** [makefile_base:114: suzuki_tables.o] Error 1
make: *** Waiting for unfinished jobs....

/home/stephen/MESA/mesa/rates/make
FAILED

/home/stephen/MESA/mesa/rates
./build_and_test FAILED

I don't know what to do now, can someone help me？

**Comment by pmocz** [comment] 2024-07-15 11:12
I'm happy to take a look at this! Which version of Mesa are you using?

**Comment by gzyasdafaegfea** [comment] 2024-07-15 13:04
I am using mesa-r12778,maybe it's too old, should i update a newer one?

**Comment by fxt44** [comment] 2024-07-15 14:09
follow the best practices for reporting a problem when installing: 

https://docs.mesastar.org/en/release-r24.03.1/installation.html

especially the last item on the page of posting your $MESA_DIR/build.log .

**Comment by gzyasdafaegfea** [comment] 2024-07-15 14:17
Oh sorry, i have solved the problem, just update the mesa version. I am so sorry to disturb you.

**Comment by pmocz** [comment] 2024-07-15 14:21
If you can, try out the latest version to see if it solves your problem and has all the features you need
[r24.03.1](https://github.com/MESAHub/mesa/releases/tag/r24.03.1).
If it does not work, you may try out an older version:
[r15140](https://github.com/MESAHub/mesa/releases/tag/r15140)
which is the oldest version hosted on github.
If you find a version that works for your problem, please let us know. If not then I can help debug if I am given a reproducer

**Comment by fxt44** [comment] 2024-07-15 14:27
> It seems like to be a specific bug in old version

ahh, now i remember. to build r12778 with a modern sdk one needs to apply a patch file:

% patch -p1 < 0001-Collected-changes-needed-to-build-r12778-with-gfortr.patch

where the patch file itself is 

[0001-Collected-changes-needed-to-build-r12778-with-gfortr.patch](https://github.com/user-attachments/files/16235968/0001-Collected-changes-needed-to-build-r12778-with-gfortr.patch)

i know this works because eb and i did it very recently.

**Comment by Debraheem** [comment] 2024-07-19 17:33
I think Frank provided an adequate solution for installing r12778, so I will close this issue thread now.

**Closed by Debraheem** 2024-07-19 17:33 UTC
