### ISSUE TITLE
Overshoot causes models to crash near CC

### ISSUE THREAD

**Issue by rjfarmer** [MESAHub/mesa#400] opened 2022-04-14 18:29 UTC
See https://logs.mesastar.org/f80496c1883b11379c017aa884c541837ba78a0a/cannon_conroy_intel/12M_pre_ms_to_core_collapse/out.txt as an example (but i have seen this on main and with various overshoot settings).

The main error is this:

````
 k, k_a, k_b          55          55          55
 s%top_conv_bdy(i)= T
 D(k)   0.0000000000000000     
 s%D_mix(k+1)  0.84742704178042305     
 s%overshoot_D_min   100.00000000000000     
 Invalid location for overshoot boundary: cz_bdy_dq, dq=   4.9640111325885146E-006   4.2066372694545603E-008
terminated evolution: nonzero_ierr
````

That is coming from around https://github.com/MESAHub/mesa/blob/152d7a20eaa52039fed60446840ea9a8baefd3c2/star/private/overshoot.f90#L245

I don't know why we have started having this problem with this release but I'm finding it very hard to get massive star models to collapse due to this.

**Comment by fxt44** [comment] 2022-05-18 13:57
wild shot, tdc on?

**Comment by KarelTemmink** [comment] 2022-05-19 12:14
Dear devs,
I'm running into the same issue simulating low- to intermediate (1-8Msun) stars with version mesa-r22.05.1. 
A typical example is during the He-flash, near the moment the burning flame reaches the center of the star.
I have recently reported this issue on the mailing list: [https://lists.mesastar.org/pipermail/mesa-users/2022-May/013707.html](here), but I also attach the relevant files for reproducing this error here: [overshooting_issue_files.zip](https://github.com/MESAHub/mesa/files/8728930/overshooting_issue_files.zip).

-Karel Temmink

**Comment by KarelTemmink** [comment] 2022-05-20 19:20
> Dear devs, I'm running into the same issue simulating low- to intermediate (1-8Msun) stars with version mesa-r22.05.1. A typical example is during the He-flash, near the moment the burning flame reaches the center of the star. I have recently reported this issue on the mailing list: [https://lists.mesastar.org/pipermail/mesa-users/2022-May/013707.html](here), but I also attach the relevant files for reproducing this error here: [overshooting_issue_files.zip](https://github.com/MESAHub/mesa/files/8728930/overshooting_issue_files.zip).
> 
> -Karel Temmink

Actually, I'd also like to report this issue in version r21.12.1, with similar inlists as above.

**Comment by rjfarmer** [comment] 2022-05-24 10:46
> wild shot, tdc on?

Yes, turning off TDC and doing a restart or running with TDC off from the beginning does fix things. Whether that is just us perturbing the model though, i don't know.

Though Karels reporting it with both 22.05.1 (default TDC on) and 21.12.1 (defaults with TDC off)

**Comment by fxt44** [comment] 2022-05-24 17:49
yea, the report of it happening in 21.12.1 made it moot. i can't recall any commits that directly modified the overshooting prescriptions, so i was poking around for things that might change the calculation of cz_bdy_dq.

**Comment by orlox** [comment] 2022-06-30 15:25
FYI, just run into a case of this while making MESA6 models on the latest dev version. I can restart with TDC on or off and still get the same issue, so its definitely unrelated to that choice. I will just bite the bullet and dig into it.

**Comment by orlox** [comment] 2022-06-30 16:46
And I think I have it. This can happen in a single cell convective region, or more generally in a convective region that is below the value of `overshoot_D_min`. That's at least what was going on in my case, and this particular part of the error is telling
`k, k_a, k_b          55          55          55`
That says that the bottom of the overshoot zone 'k_a' is the same as the top `k_b`. In my particular case that had this error the code is trying to find the precise fraction dq of the cell which is convective, by doing

```
s%cz_bdy_dq(k) = find0(0._dp, D(k)-s%overshoot_D_min, s%dq(k), s%D_mix(k+1)-s%overshoot_D_min)
```
and I had a single convective face where D_mix from convection is puny and below overshoot_D_min. The code tries to check D_mix(k+1) which is not convective and has a mixing coefficient of zero. So both cells are below the threshold of overshoot_D_min, and the root finder gives nonsense. I could imagine that the same thing is possible in cases where convection covers more than one cell, but convection is puny and below overshoot_D_min throughout the region.

```
                if (s%top_conv_bdy(i)) then
                   if (s%D_mix(k+1) > s%overshoot_D_min) then
                      s%cz_bdy_dq(k) = find0(0._dp, D(k)-s%overshoot_D_min, s%dq(k), s%D_mix(k+1)-s%overshoot_D_min)
                      if (s%cz_bdy_dq(k) < 0._dp .OR. s%cz_bdy_dq(k) > s%dq(k)) then
                         write(*,*) 'k, k_a, k_b', k, k_a, k_b 
                         write(*,*) 's%top_conv_bdy(i)=', s%top_conv_bdy(i)
                         write(*,*) 'D(k)', D(k)
                         write(*,*) 's%D_mix(k+1)', s%D_mix(k+1)
                         write(*,*) 's%overshoot_D_min', s%overshoot_D_min
                         write(*,*) 'Invalid location for overshoot boundary: cz_bdy_dq, dq=', s%cz_bdy_dq(k), s%dq(k)
                         ierr = -1
                         return
                      end if
                   end if
                else
                   s%cz_bdy_dq(k-1) = find0(0._dp, s%D_mix(k-1)-s%overshoot_D_min, s%dq(k-1), D(k)-s%overshoot_D_min)
                   if (s%D_mix(k-1) > s%overshoot_D_min) then
                      if (s%cz_bdy_dq(k-1) < 0._dp .OR. s%cz_bdy_dq(k-1) > s%dq(k-1)) then
                         write(*,*) 'k, k_a, k_b', k, k_a, k_b 
                         write(*,*) 's%top_conv_bdy(i)=', s%top_conv_bdy(i)
                         write(*,*) 'D(k)', D(k)
                         write(*,*) 's%D_mix(k-1)', s%D_mix(k-1)
                         write(*,*) 's%overshoot_D_min', s%overshoot_D_min
                         write(*,*) 'Invalid location for overshoot boundary: cz_bdy_dq, dq=', s%cz_bdy_dq(k-1), s%dq(k)
                         ierr = -1
                         return
                      end if
                   end if
                endif
```
I've committed a small check to see that the root find will not do nonsense, have this within a different branch I'm working on and it does not appear to have broken anything at the moment
https://testhub.mesastar.org/superad_reduction/commits/98902d0

**Comment by evbauer** [comment] 2022-06-30 18:46
Nice work! Is it possible this issue has been lurking around since 12778 (March 2020)? That's when the "new" overshoot controls got turned on by default and the old ones were removed. https://docs.mesastar.org/en/release-r22.05.1/changelog.html#new-overshooting-controls

Digging back further, it does look like the old overshoot controls had a zone check (`k < k0`) that would have guarded against encountering this error for the first zone in the loop (and hence for single-cell convective zones).

**Comment by orlox** [comment] 2022-06-30 19:26
I have surely been running into this for over a year, don't know is as far back as pre-covid times. If we'd like to double check what I think is the issue, it should be straightforward to reproduce just by artificially making (in the right place) one zone as `mixing_type=convective_mixing` with a mixing coefficient below `overshoot_D_min`.

**Comment by rjfarmer** [comment] 2022-06-30 19:39
Could you add some comments so we know what's happening here in case we run in to this again?

**Comment by orlox** [comment] 2022-07-06 14:47
Simple way to trigger this, just to verify the cause is what I think it is. In mix_info.f90, one can add this at the beginning of `locate_convection_boundaries`:

```
         !add a convective region below overshoot_D_min to trigger error
         write(*,*) "check solver_iter", s% solver_iter
         if (s% solver_iter <= 0) then 
            do k=s% nz-10, 10, -1
               if (s% q(k) >0.7d0 .or. s% q(k) <0.6d0) then 
                   cycle
               end if
               if (s% mixing_type(k) == no_mixing .and. s% mixing_type(k-1) == no_mixing .and. s% mixing_type(k+1) == no_mixing) then 
                  s% D_mix(k-10:k) = s% overshoot_D_min/2d0
                  s% mixing_type(k-10:k) = convective_mixing
                  write(*,*) "added single cell D_mix at k=", k, s% D_mix(k), s% mixing_type(k)
                  exit
               end if
            end do
         end if
```
This adds up a convection zone in an arbitrary location, with a constant Dmix below the overshoot threshold. The following work directory will then crash immediately (basic work directory for a 15 Msun star with overshooting on shells):
[work2.tar.gz](https://github.com/MESAHub/mesa/files/9055720/work2.tar.gz)

So as I was thinking, you do not need a single cell region, having a region with puny mixing coming out of MLT or TDC should be enough. I'll make the PR to merge this later today.

**Comment by orlox** [comment] 2022-07-21 05:53
all-green testhub so closing now

**Closed by orlox** 2022-07-21 05:53 UTC
Labels: bug, release-blocker
